version: '3.1'

services:
  jupyter:
    image: jupyter/tensorflow-notebook
    restart: always
    ports:
      - 31002:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    deploy:
      resources:
        limits:
          memory: 256M